### ISSUE TITLE
没有读取RAW里的required设定是否为可选型

### ISSUE THREAD

**Issue by xueyongwei** [CodeOcenS/SwiftJSONModeler#2]
使用Raw创建model的时候，optionalStr 只是根据配置里的进行了设置，觉得应该使用YAPI的Raw里的required字段标记的。

**Comment by CodeOcenS** [comment]
其实也不是没想过，但是由于我们的后台不能保证 required 字段有的情况下，字段一定会有值，所以就统一控制了。

**Comment by xueyongwei** [comment]
额，好吧。这其实是他们不合理，反倒我们受其害...
